version: '3.8'
services:
  nginx-react:
    container_name: eficens-review-app
    build:
      dockerfile: Dockerfile.prod
    image: eficens-review-app
    ports:
      - 8080:80
      - 3000:3000
    environment:
      VITE_API_URL: https://jsonplaceholder.typicode.com/
